# ROS Message (from tablet to robot)


# flag for canvas scaling up 
bool isScalingUp

# flag for canvas scaling down
bool isScalingDown

# on pointer click
bool pointerClick
float32[] pointerPosition

# is dragging the view
bool isDragging

# on pointer clicking an clickable object
string clickedObjectName

# on pinch the screen
bool onPinch

# speaking start, end, speaking, no speaking
string speakingStage

