# Message for logging from the Unity tap game
Header header

string message

string CHECK_IN = 0
string GAME_START_PRESSED = 1
string INIT_ROUND_DONE = 2
string START_ROUND_DONE = 3
string ROBOT_RING_IN = 4
string PLAYER_RING_IN = 5
string RESET_NEXT_ROUND_DONE = 6
string SHOW_GAME_END_DONE = 7
string START_PRONUNCIATION_PANEL_DONE = 8
string END_PRONUNCIATION_PANEL_DONE = 9
string SHOW_RESULTS_DONE = 10