# Message for logging from the Unity tap game
Header header

int32 message
string params

int32 CHECK_IN = 0
int32 GAME_START_PRESSED = 1
int32 INIT_ROUND_DONE = 2
int32 START_ROUND_DONE = 3
int32 ROBOT_RING_IN = 4
int32 PLAYER_RING_IN = 5
int32 START_PRONOUNCE = 6
int32 END_ROUND_DONE = 7
int32 RESET_NEXT_ROUND_DONE = 8
int32 SHOW_GAME_END_DONE = 9
int32 PLAYER_BEAT_ROBOT = 10
int32 RESTART_GAME = 11